import Head from "next/head";
import Image from "next/image";
import LatestBlogs from "../components/LatestBlogs";
import RightSection from "../components/RightSection";
import styles from "../styles/Home.module.css";
import FeaturedPosts from "../components/FeaturedPosts";

export default function Home() {
  return (
    <div>
      <Head>
        <title>AniLog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto p-8">
        <h1 className="font-bangers text-6xl tracking-wider text-center mb-2">
          Anilog
        </h1>
        <p className="font-montserrat mx-auto text-center mb-16 text-lg pb-2 border-b-2 border-b-error w-3/4">
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aspernatur,
          molestias!
        </p>
        <FeaturedPosts />
        <section className={styles.home_grid}>
          <LatestBlogs />
          <RightSection />
        </section>
      </main>
    </div>
  );
}
