import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import RightSection from "../../components/RightSection";
import BlogBody from "../../components/BlogBody";
import ReadMore from "../../components/ReadMore";
import styles from "../../styles/Home.module.css";

const Slug = () => {
  const router = useRouter();
  const { slug } = router.query;

  return (
    <>
      <Head>
        <title>AniLog - {slug}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto p-8 flex flex-col items-center justify-center">
        <div className="ad bg-secondary w-3/4 h-36 mb-8">Ad</div>
        <section
          className={`${styles.home_grid} border-b-2 border-b-gray-700 mb-8`}
        >
          <BlogBody />
          <RightSection />
        </section>
        <div className="ReadNext w-full mb-8">
          <h2 className="text-3xl font-bangers text-neutral-content border-b-4 border-error w-fit tracking-wider mb-4">
            Read More
          </h2>
          <ReadMore />
        </div>
        <div className="ad bg-secondary w-3/4 h-36 mb-8">Ad</div>
      </main>
    </>
  );
};

export async function getServerSideProps(context) {
  let navCategories;
  let headers = {
    Authorization: `Bearer ${process.env.BEARER_TOKEN}`,
  };

  try {
    const res = await fetch("http://localhost:1337/api/categories", {
      headers: headers,
    });
    const json = await res.json();
    navCategories = json.data;
  } catch (error) {
    throw new Error(error);
  }

  return {
    props: { navCategories }, // will be passed to the page component as props
  };
}

export default Slug;
