import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import LatestBlogs from "../../components/LatestBlogs";
import RightSection from "../../components/RightSection";
import styles from "../../styles/Home.module.css";

const Slug = ({ getCategories, navCategories }) => {
  const router = useRouter();
  const { slug } = router.query;

  return (
    <div>
      <Head>
        <title>AniLog - {slug}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="upper_intro mx-auto w-full flex flex-col justify-center items-center">
        <h1 className="font-bangers tracking-widest text-center text-5xl my-8">
          {slug}
        </h1>
        <p className="font-montserrat text-center mb-8 w-10/12">
          {navCategories.map((category) => {
            return (
              category.attributes.type === slug &&
              category.attributes.typeDescription
            );
          })}
        </p>
      </div>
      <main className="container mx-auto p-8">
        <section className={styles.home_grid}>
          <LatestBlogs />
          <RightSection />
        </section>
      </main>
    </div>
  );
};

export async function getServerSideProps(context) {
  let navCategories;
  let headers = {
    Authorization: `Bearer ${process.env.BEARER_TOKEN}`,
  };

  try {
    const res = await fetch("http://localhost:1337/api/categories", {
      headers: headers,
    });
    const json = await res.json();
    navCategories = json.data;
  } catch (error) {
    throw new Error(error);
  }

  return {
    props: { navCategories }, // will be passed to the page component as props
  };
}

export default Slug;
