import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import CategoryLatestBlogs from "../../components/CategoryLatestBlogs";
import RightSection from "../../components/RightSection";
import styles from "../../styles/Home.module.css";

const Slug = ({ getCategories, navCategories, blogData }) => {
  const router = useRouter();
  const { slug } = router.query;

  return (
    <div>
      <Head>
        <title>AniLog - {slug}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="upper_intro mx-auto w-full flex flex-col justify-center items-center">
        <h1 className="font-bangers tracking-widest text-center text-4xl sm:text-5xl my-4 sm:my-8">
          {slug}
        </h1>
        <p className="font-montserrat text-sm sm:text-base text-center mb-4 sm:mb-8 w-10/12">
          {navCategories.map((category) => {
            return (
              category.attributes.type === slug &&
              category.attributes.typeDescription
            );
          })}
        </p>
      </div>
      <main className="container mx-auto px-8 sm:p-8">
        <section className={styles.home_grid}>
          <CategoryLatestBlogs blogData={blogData} checkSlug={slug} />
          <RightSection blogData={blogData} />
        </section>
      </main>
    </div>
  );
};

export async function getServerSideProps(context) {
  let navCategories;
  let blogData;
  let headers = {
    Authorization: `Bearer ${process.env.BEARER_TOKEN}`,
  };

  try {
    const [res1, res2] = await Promise.all([
      fetch("http://localhost:1337/api/categories", {
        headers: headers,
      }),
      fetch(
        "http://localhost:1337/api/blog-posts?populate=*&sort=createdAt%3Adesc",
        {
          headers: headers,
        }
      ),
    ]);
    const [json1, json2] = await Promise.all([res1.json(), res2.json()]);
    navCategories = json1.data;
    blogData = json2.data;
  } catch (error) {
    throw new Error(error);
  }

  return {
    props: { navCategories, blogData }, // will be passed to the page component as props
  };
}

export default Slug;
