import React from "react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import styles from "../../styles/Home.module.css";
import RightSection from "../../components/RightSection";
import AuthorLatestBlogs from "../../components/AuthorLatestBlogs";

const Slug = ({ navCategories, blogData, authorDetails }) => {
  const router = useRouter();
  const { slug } = router.query;

  // console.log(authorDetails);

  return (
    <div>
      <Head>
        <title>{authorDetails[0].attributes.authorName.toUpperCase()}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-8 sm:p-8">
        <section className={styles.home_grid}>
          <div>
            <div className="author my-8">
              <div className="flex flex-col items-center justify-center md:items-start md:justify-start">
                <Image
                  src={`http://localhost:1337${authorDetails[0].attributes.authorImg.data.attributes.url}`}
                  // src="/manga.jpg"
                  width={120}
                  height={120}
                  className="rounded-full"
                />
                <div className="mt-8">
                  <h3 className="font-bangers text-3xl tracking-wider text-center md:text-left">
                    {authorDetails[0].attributes.authorName}
                    {/* Sayan Munshi */}
                  </h3>
                  <p className="font-montserrat text-center sm:text-left">
                    {authorDetails[0].attributes.authorDesc}
                    {/* Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Quod, totam sequi. Soluta dolores maiores nemo, ipsam quam
                    iure? Ipsam perspiciatis at fugit sed perferendis officia
                    facere saepe velit consequatur id? */}
                  </p>
                </div>
              </div>
            </div>
            <div>
              <h2 className="text-3xl font-bangers text-neutral-content border-b-4 border-error w-fit tracking-wider mb-4">
                Latest Blogs By {authorDetails[0].attributes.authorName}
              </h2>
              <AuthorLatestBlogs
                blogData={blogData}
                checkAuthorSlug={authorDetails[0].attributes.slug}
              />
            </div>
          </div>
          <RightSection blogData={blogData} />
        </section>
      </main>
    </div>
  );
};

export async function getServerSideProps(context) {
  let navCategories;
  let blogData;
  let authorDetails;
  let headers = {
    Authorization: `Bearer ${process.env.BEARER_TOKEN}`,
  };

  try {
    const [res1, res2, res3] = await Promise.all([
      fetch("http://localhost:1337/api/categories", {
        headers: headers,
      }),
      fetch(
        "http://localhost:1337/api/blog-posts?populate=*&sort=createdAt%3Adesc",
        {
          headers: headers,
        }
      ),
      fetch(
        `http://localhost:1337/api/authors?filters[slug]=${context.query.slug}&populate=*`,
        {
          headers: headers,
        }
      ),
    ]);
    const [json1, json2, json3] = await Promise.all([
      res1.json(),
      res2.json(),
      res3.json(),
    ]);
    navCategories = json1.data;
    blogData = json2.data;
    authorDetails = json3.data;
  } catch (error) {
    throw new Error(error);
  }

  return {
    props: { navCategories, blogData, authorDetails }, // will be passed to the page component as props
  };
}

export default Slug;
